"""added rider relationships

Revision ID: 04302840334f
Revises: 5b15af1080ec
Create Date: 2024-10-02 15:59:55.014114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04302840334f'
down_revision = '5b15af1080ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_stop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_riders_my_stop_id_stations'), 'stations', ['my_stop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_riders_my_stop_id_stations'), type_='foreignkey')
        batch_op.drop_column('my_stop_id')

    # ### end Alembic commands ###
