"""added line_gtfs_endpoint table

Revision ID: 4e1cf30f97ef
Revises: e2786c7860db
Create Date: 2024-09-27 11:29:48.452333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1cf30f97ef'
down_revision = 'e2786c7860db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_gtfs_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lines', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_gtfs_endpoints'))
    )
    with op.batch_alter_table('all_subway_stations', schema=None) as batch_op:
        batch_op.alter_column('cbd',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('gtfs_latitude',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('gtfs_longitude',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_subway_stations', schema=None) as batch_op:
        batch_op.alter_column('gtfs_longitude',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('gtfs_latitude',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('cbd',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    op.drop_table('line_gtfs_endpoints')
    # ### end Alembic commands ###
