"""added unique constraint to username

Revision ID: 5361b8ab85c5
Revises: ddad806243de
Create Date: 2024-10-04 15:20:00.517291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5361b8ab85c5'
down_revision = 'ddad806243de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_riders_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_riders_username'), type_='unique')

    # ### end Alembic commands ###
