"""adding relationships

Revision ID: 5b15af1080ec
Revises: 88e13c77de77
Create Date: 2024-10-02 15:58:57.754513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b15af1080ec'
down_revision = '88e13c77de77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_riders_my_stop_id_stations', type_='foreignkey')
        batch_op.drop_column('my_stop_id')

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_stop_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_stop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_routes_end_stop_id_stations'), 'stations', ['end_stop_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_routes_start_stop_id_stations'), 'stations', ['start_stop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_routes_start_stop_id_stations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_routes_end_stop_id_stations'), type_='foreignkey')
        batch_op.drop_column('end_stop_id')
        batch_op.drop_column('start_stop_id')

    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_stop_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_riders_my_stop_id_stations', 'stations', ['my_stop_id'], ['id'])

    # ### end Alembic commands ###
