"""trying to update riders and routes

Revision ID: 60279d85050e
Revises: 88e13c77de77
Create Date: 2024-10-02 18:00:02.577172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60279d85050e'
down_revision = '88e13c77de77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_riders_my_stop_id_stations', type_='foreignkey')
        batch_op.drop_column('my_stop_id')

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_routes_rider_id_riders', type_='foreignkey')
        batch_op.drop_column('rider_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rider_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_routes_rider_id_riders', 'riders', ['rider_id'], ['id'])

    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_stop_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_riders_my_stop_id_stations', 'stations', ['my_stop_id'], ['id'])

    # ### end Alembic commands ###
