"""changed station endpoin to station endpoints

Revision ID: 6939f18112af
Revises: d47d87e1adb8
Create Date: 2024-09-27 13:48:11.562206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6939f18112af'
down_revision = 'd47d87e1adb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('fk_station_endpoints_endpoint_id_endpoints')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_station_endpoints_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station_endpoints'))
    )
    op.drop_table('station_endpoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_endpoint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('station_id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name='fk_station_endpoint_endpoint_id_endpoints'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='fk_station_endpoint_station_id_stations'),
    sa.PrimaryKeyConstraint('id', name='pk_station_endpoint')
    )
    op.drop_table('station_endpoints')
    # ### end Alembic commands ###
