"""added rider my_stops

Revision ID: ddad806243de
Revises: 60279d85050e
Create Date: 2024-10-02 18:03:21.838021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddad806243de'
down_revision = '60279d85050e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_stop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_riders_my_stop_id_stations'), 'stations', ['my_stop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_riders_my_stop_id_stations'), type_='foreignkey')
        batch_op.drop_column('my_stop_id')

    # ### end Alembic commands ###
