"""initial migration

Revision ID: e2786c7860db
Revises: 
Create Date: 2024-09-26 17:33:49.124969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2786c7860db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_subway_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gtfs_stop_id', sa.String(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('complex_id', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('stop_name', sa.String(), nullable=True),
    sa.Column('borough', sa.String(), nullable=True),
    sa.Column('cbd', sa.Boolean(), nullable=True),
    sa.Column('daytime_routes', sa.String(), nullable=True),
    sa.Column('structure', sa.String(), nullable=True),
    sa.Column('gtfs_latitude', sa.Float(), nullable=True),
    sa.Column('gtfs_longitude', sa.Float(), nullable=True),
    sa.Column('north_direction_label', sa.String(), nullable=True),
    sa.Column('south_direction_label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_all_subway_stations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_subway_stations')
    # ### end Alembic commands ###
