"""added rider and route classes with relationships

Revision ID: e621476d4cf6
Revises: 2e6d7e2bceee
Create Date: 2024-09-27 17:23:54.270328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e621476d4cf6'
down_revision = '2e6d7e2bceee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('fav_subway_activity', sa.String(), nullable=True),
    sa.Column('my_stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['my_stop_id'], ['stations.id'], name=op.f('fk_riders_my_stop_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_riders'))
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.Column('route_type', sa.String(), nullable=True),
    sa.Column('rider_id', sa.Integer(), nullable=True),
    sa.Column('start_stop_id', sa.Integer(), nullable=True),
    sa.Column('end_stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_stop_id'], ['stations.id'], name=op.f('fk_routes_end_stop_id_stations')),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_routes_rider_id_riders')),
    sa.ForeignKeyConstraint(['start_stop_id'], ['stations.id'], name=op.f('fk_routes_start_stop_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_table('riders')
    # ### end Alembic commands ###
