"""lots of big changes

Revision ID: fbec52a34f3f
Revises: 04302840334f
Create Date: 2024-10-02 17:29:43.510773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec52a34f3f'
down_revision = '04302840334f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_endpoints')
    op.drop_table('endpoints')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lines', sa.VARCHAR(), nullable=True),
    sa.Column('endpoint', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_endpoints')
    )
    op.create_table('station_endpoints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('station_id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=False),
    sa.Column('route', sa.VARCHAR(), nullable=True),
    sa.Column('station_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name='fk_station_endpoints_endpoint_id_endpoints'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='fk_station_endpoints_station_id_stations'),
    sa.PrimaryKeyConstraint('id', name='pk_station_endpoints')
    )
    # ### end Alembic commands ###
